### ISSUE TITLE
LOS Line colours change to default when switching to multishot

### ISSUE THREAD

**Issue by LadyAlekto** [Sheep-y/Attack-Improvement-Mod#8]
![20180709030453_1](https://user-images.githubusercontent.com/39632036/42426082-48729f0e-8325-11e8-9b63-8a39920b59a7.jpg)

**Comment by LadyAlekto** [comment]
![20180709030456_1](https://user-images.githubusercontent.com/39632036/42426088-54afaea6-8325-11e8-869c-ac0cb67a93b0.jpg)

**Comment by Sheep-y** [comment]
That's quick lol.  Yes, I wasn't sure how to move forward, and I figured I'll get the basic right first.  I think I'll add three widths to keep it simple, instead of duplicating the styles or switch to some other format.

**Comment by LadyAlekto** [comment]
Maybe get into contact with janxious for parts of his code, he was busy but we spoke about yours concerning that AIM may override it for RT or if issues could arise

https://github.com/janxious/BTMLColorLOSMod

**Comment by Sheep-y** [comment]
Janxious's BTMLColorLOSMod mod is a good one that inspired me to make my life easier.  But I don't intend to replace that mod's more advanced function like multi-colour set and changing them on keypress.  The fact that the mod has a pretty restricted set of permission and the lack of license is also making me stay away since I don't want to risk plagiarising or code copyright issue.

I've been looking at Harmony and ModTek's priority system, to see if I can make it so that when BTMLColorLOSMod is installed, I can disable my LOS changes.  So, if a player wants something simple that works out of box (s)he can install AIM and be done with this part.  If they want more customisations and controlls they can install BTMLColorLOSMod without worring about conflict.  At least that is my plan.

**Comment by LadyAlekto** [comment]
Considering some discussions on the discord, such a piece of code would be highly appreciated (checking for possible issues and switching parts of yours off or on if another is present)

**Comment by Sheep-y** [comment]
Requesting a [modtek feature](https://github.com/Mpstark/ModTek/issues/75) as a first step.

Meanwhile, it is still doable, just more difficult both in flow and technique.  A bit disappointing but still has to be done.

**Comment by LadyAlekto** [comment]
I personally argue if you make this into the ultimate aim stuff mod, youd be golden

And somehwhat selfish thinking "I could reduce size and clutter in my package"


Though id also argue to move the settings into a settings (more for convenience but this is the wrong issue for that)

**Comment by Sheep-y** [comment]
Yes I have been thinking about individual an setting file too.  I also saw a related discussion on ModTek page.

I may be able to solve that and a few other concerns by making a mod helper class, not only for me but also for other modders.  But for now I have to stop adding new things to focus on polishing, testing, documenting, and pushing the existing changes out.

Fixing Multi-Target and a refining a few other things now.

**Comment by Sheep-y** [comment]
Should have fixed LOS issues.  Checked BTMLColorLOSMod.  janxious's completely recoded the line drawing, while I pre-made the line materials when player first enter combat and let the game's original function reuse them.

I'll now do "melee after sprint" and then feature freeze AIM.  Once it's frozen I can separate settings out and sort out mod incompatibilities.
